FROM timberio/vector:0.18.1-debian as logshipper

RUN apt update \
    && apt install -y \
    gettext \
    && rm -rf /var/cache/apt

RUN mkdir -p /etc/vector/certificates

COPY *.yaml /etc/vector/
COPY *.template /etc/vector/
COPY start.sh .

ENV LOG warn

ENTRYPOINT [ "bash" ]

CMD [ "start.sh" ]
