version: '2.1'
services:
  transformer-runner:
    build: ./transformer-runner
    restart: always
    volumes:
      - shared:/shared
    labels:
      io.balena.features.balena-socket: '1'
      io.balena.features.supervisor-api: '1'
    environment:
      REGISTRY_HOST: "registry"
      REGISTRY_PORT: "5000"

  # The registry is needed for dev only
  registry:
    image: "registry:2.7.1"
    cap_add:
      - SYS_RESOURCE
      - SYS_ADMIN
    security_opt:
      - "apparmor:unconfined"
    volumes:
      - "registry-data:/data"
    tmpfs:
      - /run
      - /sys/fs/cgroup

volumes:
  registry-data: {}
  garbage-collector: {}
  shared: {}
