version: '2.1'
services:
  transformer-runner:
    build: ./transformer-runner
    restart: always
    privileged: true
    volumes:
      - shared:/shared

  fleet-launcher:
    build: ./fleet-launcher
    restart: always
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-socket: '1'
    depends_on:
      - transformer-runner
    volumes:
      - shared:/shared

  garbage-collector:
    build: ./garbage-collector
    restart: always
    environment:
      - DOCKER_HOST=unix:///var/run/balena-engine.sock
    labels:
      io.balena.features.balena-socket: '1'
    volumes:
      - garbage-collector:/root

volumes:
  registry-data: {}
  garbage-collector: {}
  shared: {}
