version: '2.1'
services:
  transformer-runner:
    build: ./transformer-runner
    restart: always
    privileged: true
    volumes:
      - shared:/shared
    environment:
      REGISTRY_HOST: "registry.ly.fish"
      WORKER_JF_TOKEN: "foobar"
      JF_API_URL: "https://jel.ly.fish"
      JF_API_PREFIX: "api/v2"

volumes:
  registry-data: {}
  garbage-collector: {}
  shared: {}
