version: '2.1'
services:
  registry:
    image: "registry:2.7.1"
    volumes:
      - "registry-data:/data"

  dev-artifact-provider:
    build: ./dev-artifact-provider
    privileged: true
    environment:
      REGISTRY_HOST: "registry"
      REGISTRY_PORT: "5000"
    depends_on:
      - registry

  jellyfish-mock:
    build: ./jellyfish-mock
