version: '2.1'
services:
  transformer-runner:
    build: ./transformer-runner
    restart: always
    privileged: true
    volumes:
      - shared:/shared
    environment:
      REGISTRY_HOST: "registry"
      REGISTRY_PORT: "5000"
      WORKER_JF_TOKEN: "foobar"
      JF_API_URL: "http://jellyfish-mock:3000"
      JF_API_PREFIX: "api/v2"
      
  registry:
    image: "registry:2.8.0"
    volumes:
      - "registry-data:/data"

  dev-artifact-provider:
    build: ./dev-artifact-provider
    privileged: true
    environment:
      REGISTRY_HOST: "registry"
      REGISTRY_PORT: "5000"
    depends_on:
      - registry

  jellyfish-mock:
    build: ./jellyfish-mock
