version: '2.1'
services:
  transformer-runner:
    build: ./transformer-runner
    restart: always
    privileged: true
    volumes:
      - shared:/shared
      - shared-docker-socket:/var/run
      - docker-storage:/var/lib/docker

  fleet-launcher:
    build: ./fleet-launcher
    restart: always
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-socket: '1'
    depends_on:
      - transformer-runner
    volumes:
      - shared:/shared

  garbage-collector:
    image: stephanmisc/docuum:0.16.1
    restart: always
    command: --threshold '4 GB'
    depends_on:
      - transformer-runner
    volumes:
      - garbage-collector:/root
      - shared-docker-socket:/var/run

  # this auto-registers QEMU to run non-native binaries
  # can be leveraged for `docker build --platform=linux/arm64` etc
  binfmt-hook:
    image: multiarch/qemu-user-static
    command: [ '--reset', '-p', 'yes' ]
    privileged: true
    restart: 'no'

  logshipper:
    build:
        context: ./logshipper
    environment:
      LOG: warn
    labels:
      io.balena.features.journal-logs: '1'
    restart: unless_stopped
    volumes:
        - 'logshipper-data:/var/lib/logshipper'

volumes:
  registry-data: {}
  garbage-collector: {}
  shared: {}
  shared-docker-socket: {}
  docker-storage: {}
  logshipper-data: {}
