export enum TaskStatus {
    Pending = 'pending',
    Accepted = 'accepted',
    Completed = 'completed',
    Failed = 'failed',
}

export enum LinkNames {
    WasBuiltInto = 'was built into',
    Generated = 'generated',
    Ran ='ran',
}

export enum LinkNamesInverse {
    WasBuiltFrom = 'was built from',
    WasGeneratedBy = 'was generated by',
    WasRunBy = 'was run by',
}
