on:
 push:
    branches:
      - master

jobs:
  balena_cloud_build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: balena-io/deploy-to-balena-action@master
        id: build
        with:
          balena_token: ${{ secrets.BALENA_API_KEY_PUSH }}
          fleet: ${{ secrets.BALENA_FLEET }}
      - name: Log release ID of build
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
      - name: Log release version of build
        run: echo "Built release ID ${{ steps.build.outputs.version }}"
