---
name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    secrets:
      FLOWZONE_TOKEN: ${{ secrets.FLOWZONE_TOKEN }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      COMPOSE_VARS: ${{ secrets.COMPOSE_VARS }}
    with:
      jobs_timeout_minutes: 60
      # https://github.com/product-os/balena-concourse/tree/master/provision/app/github-actions-runner
      #runs_on: '["self-hosted","linux","x64"]'
      required_approving_review_count: 0
